// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2SnZYbxaJK2Qx9QIXCRflYjlfdxhrBs',
    appId: '1:962205038847:web:fa92396090c87fd97a34ca',
    messagingSenderId: '962205038847',
    projectId: 'task-master-667a9',
    authDomain: 'task-master-667a9.firebaseapp.com',
    storageBucket: 'task-master-667a9.firebasestorage.app',
    measurementId: 'G-D09LC7WWH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADwMIZCDl1euhdW2wKhoJ2QdmLzMDtbQE',
    appId: '1:962205038847:android:21447b1d6d378a837a34ca',
    messagingSenderId: '962205038847',
    projectId: 'task-master-667a9',
    storageBucket: 'task-master-667a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByjcGwuTpPnbhRJextn4AnF4XahyNdBKQ',
    appId: '1:962205038847:ios:ec9a8e2500b7b7007a34ca',
    messagingSenderId: '962205038847',
    projectId: 'task-master-667a9',
    storageBucket: 'task-master-667a9.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByjcGwuTpPnbhRJextn4AnF4XahyNdBKQ',
    appId: '1:962205038847:ios:ec9a8e2500b7b7007a34ca',
    messagingSenderId: '962205038847',
    projectId: 'task-master-667a9',
    storageBucket: 'task-master-667a9.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2SnZYbxaJK2Qx9QIXCRflYjlfdxhrBs',
    appId: '1:962205038847:web:63ed09cfeb9d54b57a34ca',
    messagingSenderId: '962205038847',
    projectId: 'task-master-667a9',
    authDomain: 'task-master-667a9.firebaseapp.com',
    storageBucket: 'task-master-667a9.firebasestorage.app',
    measurementId: 'G-DJMQD48WXY',
  );
}
